# Generated by Django 4.2.4 on 2023-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_name", models.CharField(max_length=100)),
                ("audio_file", models.FileField(upload_to="audio/")),
                ("audio_size", models.IntegerField(null=True)),
                ("audio_extension", models.CharField(max_length=50, null=True)),
                ("audio_upload_date", models.DateTimeField(null=True)),
            ],
        ),
    ]
